### ISSUE TITLE
admin 403 forbidden

### ISSUE THREAD

**Issue by wagnersza** [tsuru/healthcheck-as-a-service#13]
when I try to list a hc that was not created by my team

```
$ tsuru hc list-urls whc
Traceback (most recent call last):
  File "/Users/wagnersza/.tsuru/plugins/hc", line 243, in <module>
    main(sys.argv[1], *sys.argv[2:])
  File "/Users/wagnersza/.tsuru/plugins/hc", line 235, in main
    command(cmd)(*args)
  File "/Users/wagnersza/.tsuru/plugins/hc", line 111, in list_urls
    response = proxy_request(name, "GET", url, "", headers)
  File "/Users/wagnersza/.tsuru/plugins/hc", line 51, in proxy_request
    return urllib2.urlopen(request, timeout=30)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by SelecaoGlobocom** [comment]
+1

**Comment by nedmax** [comment]
+1
